namespace WOTR_MAKING_FRIENDS.Features.EidolonFeatures.ProgressionFeatures
{
    public static class CreateProgressionFeatures
    {
        internal static void Create()
        {
            FeatureAddAbilityConsumeFear.Create();
            FeatureAbilityIncreaseSelection.Create();
            FeatureAddAbilityDivineTroth.Create();
            FeatureAddAbilityEvilEye.Create();
            FeatureAddAbilityEvilEyeArea.Create();
            FeatureAddFeatureLayOnHands.Create();
            FeatureAddSpellBane.Create();
            FeatureAddSpellBlink.Create();
            FeatureAddSpellBlur.Create();
            FeatureAddSpellBreathOfLife.Create();
            FeatureAddSpellCrushingDespair.Create();
            FeatureAddSpellCureSeriousWounds.Create();
            FeatureAddSpellDimensionDoor.Create();
            FeatureAddSpellGoodHope.Create();
            FeatureAddSpellHaste.Create();
            FeatureAddSpellHolyAura.Create();
            FeatureAddSpellSlow.Create();
            FeatureAddSpellTrueSeeing.Create();
            FeatureAddSpellTrueStrike.Create();
            FeatureAugmentSummoningMaster.Create();
            FeatureBonusHealing.Create();
            FeatureDR10Adamantine.Create();
            FeatureDR10Evil.Create();
            FeatureDR10Magic.Create();
            FeatureDR5.Create();
            FeatureDR5Adamantine.Create();
            FeatureDR5Chaotic.Create();
            FeatureDR5Lawful.Create();
            FeatureDR5Evil.Create();
            FeatureDR5Good.Create();
            FeatureDR5Magic.Create();
            FeatureDR5Slashing.Create();
            FeatureEnergyDrainBite.Create();
            FeatureFreedomOfMovement.Create();
            FeatureFrightfulPresence.Create();
            FeatureGhostTouch.Create();
            FeatureImmunityAbilityDamage.Create();
            FeatureImmunityBleed.Create();
            FeatureImmunityDeath.Create();
            FeatureImmunityDisease.Create();
            FeatureImmunityEnergyDrain.Create();
            FeatureImmunityFortitudeSave.Create();
            FeatureImmunityMind.Create();
            FeatureImmunityParalysis.Create();
            FeatureImmunityPetrification.Create();
            FeatureImmunityPoison.Create();
            FeatureImmunityPolymorph.Create();
            FeatureImmunitySleep.Create();
            FeatureImmunityStun.Create();
            FeatureImmunityCurse.Create();
            FeatureIncoporeal.Create();
            FeatureElemental1.Create();
            FeatureElemental8.Create();
            FeatureElemental20.Create();
            FeatureMageLight.Create();
            FeatureMaximizeHealing.Create();
            FeatureModerateFortification.Create();
            FeatureResistance4Curses.Create();
            FeatureResistance4Death.Create();
            FeatureResistance4Disease.Create();
            FeatureResistance4Paralysis.Create();
            FeatureResistance4Poison.Create();
            FeatureResistance4Mind.Create();
            FeatureStorykinBonusFeat.Create();
            FeatureSuperiorSummoningMaster.Create();
        }
    }
}
